#!/usr/bin/env python3.10

import colorama
from colorama import Fore

from core.api.yandex import YaProcessor
from core.file import FileObj
from core.utils import add_args, check_file

colorama.init(autoreset=True)


def run():
    namespace = add_args()
    files_path = check_file(namespace.path)
    processor = YaProcessor()
    for file in files_path:
        f = FileObj(file, processor)
        result = f(action=namespace.action)
        print(Fore.GREEN + result)


if __name__ == '__main__':
    run()
